version: "3"

services:
  database:
    image: "postgres:latest"

    ports:
      - 6543:5432

    environment:
      POSTGRES_USER: hotuns # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: hotuns # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: lurelog # The PostgreSQL default database (automatically created at first launch)
